"""initial migration

Revision ID: 74ea95eb8283
Revises:
Create Date: 2025-07-27 16:37:03.791365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74ea95eb8283'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('topic_streams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('update_frequency', sa.Enum('HOURLY', 'DAILY', 'WEEKLY', name='updatefrequency_enum', native_enum=False), server_default='daily', nullable=False),
    sa.Column('detail_level', sa.Enum('BRIEF', 'DETAILED', 'COMPREHENSIVE', name='detaillevel_enum', native_enum=False), server_default='detailed', nullable=False),
    sa.Column('model_type', sa.Enum('SONAR', 'SONAR_PRO', 'SONAR_REASONING', 'SONAR_REASONING_PRO', 'SONAR_DEEP_RESEARCH', 'R1_1776', 'GEMINI', name='modeltype_enum', native_enum=False), server_default='sonar-reasoning', nullable=False),
    sa.Column('recency_filter', sa.String(), server_default='1d', nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('temperature', sa.Float(), server_default=sa.text('(0.7)'), nullable=False),
    sa.Column('context_history_level', sa.Enum('NONE', 'LAST_ONE', 'LAST_THREE', 'LAST_FIVE', 'ALL_SMART_LIMIT', name='contexthistorylevel_enum', native_enum=False), server_default='last_1', nullable=False),
    sa.Column('auto_update_enabled', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('topic_streams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topic_streams_id'), ['id'], unique=False)

    op.create_table('summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_stream_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sources', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_content_tokens', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['topic_stream_id'], ['topic_streams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('summaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_summaries_id'), ['id'], unique=False)

    op.create_table('deep_dive_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic_stream_id', sa.Integer(), nullable=False),
    sa.Column('summary_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['summary_id'], ['summaries.id'], ),
    sa.ForeignKeyConstraint(['topic_stream_id'], ['topic_streams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deep_dive_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deep_dive_messages_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deep_dive_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deep_dive_messages_id'))

    op.drop_table('deep_dive_messages')
    with op.batch_alter_table('summaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_summaries_id'))

    op.drop_table('summaries')
    with op.batch_alter_table('topic_streams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topic_streams_id'))

    op.drop_table('topic_streams')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
